### ISSUE TITLE
Get and store complete JNCC Satellite Images dataset

### ISSUE THREAD

**Issue by quantoidb** [cropmapteam/Scotland-crop-map#17]
Get and store complete JNCC Satellite Images dataset on UofEdin VM. 
- start with Kelso & Jedburgh images

**Comment by WilliamPetit** [comment]
I've copied the files a while ago and since more file have been upoaded on their server.
I wanted to update our VM but there is around 800GB of data and our drive has only 500GB (see #27)

As we're going to move to the EPCC server I don't think this would be useful.
Also We're planning to use the VM for the UI and I'm planning to work on a pupped configuration (i.e. #32), so it's probably better to not mix the 2 from now on.

Should we close this issue?

**Comment by quantoidb** [comment]
EPCC infra setup and operational.
